/* ============================================================
   WONDER JOURNEY OS — CURRICULUM MAP (Step 1 of the curriculum system)
   World 1: Discover the Philippines. 72 Adventures, classes Mon/Tue/Fri,
   2026-07-06 → 2026-12-18 (last teaching week of December 2026).
   Schedulable database skeleton with per-adventure Math / English / Bible /
   Value focus. Adventures with built:true already have full interactive
   content in curriculum.js. Full content is authored unit by unit (Step 3).
   ============================================================ */
const CURRICULUM_MAP = {
  world: "World 1 — Discover the Philippines",
  schedule: { classDays: ["Mon","Tue","Fri"], start: "2026-07-06", end: "2026-12-18" },
  totalAdventures: 72,
  units: [
  {
    "n": 1,
    "name": "Welcome to the Philippines",
    "adventures": [
      {
        "n": 1,
        "id": "a1",
        "title": "Mabuhay! Welcome to the Philippines",
        "unit": 1,
        "unitName": "Welcome to the Philippines",
        "week": 1,
        "date": "2026-07-06",
        "day": "Mon",
        "objective": "Meet the Philippines, its islands, and warm greetings.",
        "value": "Gratitude",
        "math": "Number sense: count islands & place value",
        "english": "Greetings & picture vocabulary",
        "bible": "Creation (Genesis 1)",
        "built": true
      },
      {
        "n": 2,
        "id": "a2",
        "title": "Island Explorers: Luzon, Visayas & Mindanao",
        "unit": 1,
        "unitName": "Welcome to the Philippines",
        "week": 1,
        "date": "2026-07-07",
        "day": "Tue",
        "objective": "Explore the three island groups and learn directions.",
        "value": "Curiosity",
        "math": "Directions & simple map scale",
        "english": "Sentences using direction words",
        "bible": "Noah's Ark & the rainbow",
        "built": true
      },
      {
        "n": 3,
        "id": "a3",
        "title": "The Filipino Flag & National Symbols",
        "unit": 1,
        "unitName": "Welcome to the Philippines",
        "week": 1,
        "date": "2026-07-10",
        "day": "Fri",
        "objective": "Learn the flag's colors, sun and stars and their meaning.",
        "value": "Respect",
        "math": "Counting & patterns (8 rays, 3 stars)",
        "english": "Color & noun vocabulary",
        "bible": "God's promises kept",
        "built": true
      },
      {
        "n": 4,
        "id": "a4",
        "title": "First Words: Tagalog & Hiligaynon Greetings",
        "unit": 1,
        "unitName": "Welcome to the Philippines",
        "week": 2,
        "date": "2026-07-13",
        "day": "Mon",
        "objective": "Practice everyday greetings in both languages.",
        "value": "Friendliness",
        "math": "Numbers 1–10 in Filipino",
        "english": "Speaking & listening",
        "bible": "Many languages (Babel), one God",
        "built": false
      },
      {
        "n": 5,
        "id": "a5",
        "title": "Reading a Map: World → Asia → Philippines",
        "unit": 1,
        "unitName": "Welcome to the Philippines",
        "week": 2,
        "date": "2026-07-14",
        "day": "Tue",
        "objective": "Zoom in from the world to our islands using maps.",
        "value": "Wonder",
        "math": "Map grids & the compass rose",
        "english": "Reading a simple map key",
        "bible": "Abraham's journey of faith",
        "built": false
      },
      {
        "n": 6,
        "id": "a6",
        "title": "Our Wonder Journey Passport & Backpack",
        "unit": 1,
        "unitName": "Welcome to the Philippines",
        "week": 2,
        "date": "2026-07-17",
        "day": "Fri",
        "objective": "Set up our passport and backpack for the journey.",
        "value": "Readiness",
        "math": "Sorting & checklists",
        "english": "Writing our names & goals",
        "bible": "Being ready & wise (wise builder)",
        "built": false
      }
    ]
  },
  {
    "n": 2,
    "name": "Filipino Food & Kitchen",
    "adventures": [
      {
        "n": 7,
        "id": "a7",
        "title": "Kitchen Adventure: Champorado",
        "unit": 2,
        "unitName": "Filipino Food & Kitchen",
        "week": 3,
        "date": "2026-07-20",
        "day": "Mon",
        "objective": "Cook champorado while learning fractions & kitchen safety.",
        "value": "Responsibility",
        "math": "Fractions (¼ cups)",
        "english": "Sequencing: First/Next/Then",
        "bible": "Jesus feeds the 5,000",
        "built": true
      },
      {
        "n": 8,
        "id": "a8",
        "title": "Rice: The Heart of Every Meal",
        "unit": 2,
        "unitName": "Filipino Food & Kitchen",
        "week": 3,
        "date": "2026-07-21",
        "day": "Tue",
        "objective": "Discover rice, measuring cups, and simple ratios.",
        "value": "Gratitude",
        "math": "Ratios & measuring (1:2)",
        "english": "Reading a recipe",
        "bible": "Joseph stores grain in Egypt",
        "built": false
      },
      {
        "n": 9,
        "id": "a9",
        "title": "Market Day: Shopping & Money Math",
        "unit": 2,
        "unitName": "Filipino Food & Kitchen",
        "week": 3,
        "date": "2026-07-24",
        "day": "Fri",
        "objective": "Shop at a Filipino market and practice money math.",
        "value": "Stewardship",
        "math": "Money & making change",
        "english": "Writing a shopping list",
        "bible": "Honesty in our dealings",
        "built": false
      },
      {
        "n": 10,
        "id": "a10",
        "title": "Fruits of the Philippines",
        "unit": 2,
        "unitName": "Filipino Food & Kitchen",
        "week": 4,
        "date": "2026-07-27",
        "day": "Mon",
        "objective": "Taste mango, banana & buko and practice division.",
        "value": "Sharing",
        "math": "Division (sharing slices equally)",
        "english": "Descriptive words (taste, texture)",
        "bible": "Fruit of the Spirit (intro)",
        "built": false
      },
      {
        "n": 11,
        "id": "a11",
        "title": "Merienda Time: Filipino Snacks",
        "unit": 2,
        "unitName": "Filipino Food & Kitchen",
        "week": 4,
        "date": "2026-07-28",
        "day": "Tue",
        "objective": "Make a simple Filipino afternoon snack together.",
        "value": "Joy",
        "math": "Doubling a recipe",
        "english": "Speaking: describe your snack",
        "bible": "Sharing generously with others",
        "built": false
      },
      {
        "n": 12,
        "id": "a12",
        "title": "Our Family Cookbook Begins",
        "unit": 2,
        "unitName": "Filipino Food & Kitchen",
        "week": 4,
        "date": "2026-07-31",
        "day": "Fri",
        "objective": "Write our first recipe into the Family Cookbook.",
        "value": "Creativity",
        "math": "Measurement review",
        "english": "Writing clear steps (a recipe)",
        "bible": "Gratitude for daily bread",
        "built": false
      }
    ]
  },
  {
    "n": 3,
    "name": "Filipino Family & Values",
    "adventures": [
      {
        "n": 13,
        "id": "a13",
        "title": "Bayanihan: Helping Together",
        "unit": 3,
        "unitName": "Filipino Family & Values",
        "week": 5,
        "date": "2026-08-03",
        "day": "Mon",
        "objective": "Learn the Filipino spirit of community helping together.",
        "value": "Helping Others",
        "math": "Division (teamwork: 12 ÷ 4)",
        "english": "Writing about a time you helped",
        "bible": "The Good Samaritan",
        "built": true
      },
      {
        "n": 14,
        "id": "a14",
        "title": "Respect for Elders: Po, Opo & Mano",
        "unit": 3,
        "unitName": "Filipino Family & Values",
        "week": 5,
        "date": "2026-08-04",
        "day": "Tue",
        "objective": "Practice polite words and the mano gesture.",
        "value": "Respect",
        "math": "Age & time (older / younger, years)",
        "english": "Polite words & manners",
        "bible": "Honor your father & mother",
        "built": false
      },
      {
        "n": 15,
        "id": "a15",
        "title": "Filipino Hospitality: Welcoming Guests",
        "unit": 3,
        "unitName": "Filipino Family & Values",
        "week": 5,
        "date": "2026-08-07",
        "day": "Fri",
        "objective": "Discover how Filipinos warmly welcome guests.",
        "value": "Hospitality",
        "math": "Arrays: setting the table",
        "english": "Inviting & welcoming phrases",
        "bible": "Abraham welcomes three visitors",
        "built": false
      },
      {
        "n": 16,
        "id": "a16",
        "title": "Our Family Tree & Kinship Words",
        "unit": 3,
        "unitName": "Filipino Family & Values",
        "week": 6,
        "date": "2026-08-10",
        "day": "Mon",
        "objective": "Build a family tree and learn Filipino family words.",
        "value": "Family",
        "math": "Generations & simple diagrams",
        "english": "Family vocabulary",
        "bible": "Ruth's loyalty to family",
        "built": false
      },
      {
        "n": 17,
        "id": "a17",
        "title": "Kindness in Our Community",
        "unit": 3,
        "unitName": "Filipino Family & Values",
        "week": 6,
        "date": "2026-08-11",
        "day": "Tue",
        "objective": "Notice needs and plan a kind act for others.",
        "value": "Kindness",
        "math": "Tally & graph acts of kindness",
        "english": "Sentence writing",
        "bible": "Love your neighbor",
        "built": false
      },
      {
        "n": 18,
        "id": "a18",
        "title": "Family Act-of-Service Project",
        "unit": 3,
        "unitName": "Filipino Family & Values",
        "week": 6,
        "date": "2026-08-14",
        "day": "Fri",
        "objective": "Complete a hands-on service project as a family.",
        "value": "Service",
        "math": "Planning & measuring supplies",
        "english": "Reflection writing",
        "bible": "Jesus serves others (gently told)",
        "built": false
      }
    ]
  },
  {
    "n": 4,
    "name": "Festivals & Celebrations",
    "adventures": [
      {
        "n": 19,
        "id": "a19",
        "title": "Fiesta! Festivals of the Philippines",
        "unit": 4,
        "unitName": "Festivals & Celebrations",
        "week": 7,
        "date": "2026-08-17",
        "day": "Mon",
        "objective": "Discover joyful Philippine festivals, respectfully.",
        "value": "Joy",
        "math": "Arrays: counting dancers (5 × 4)",
        "english": "Festival vocabulary",
        "bible": "David dances for joy",
        "built": true
      },
      {
        "n": 20,
        "id": "a20",
        "title": "Sinulog & Ati-Atihan: Dance & Drums",
        "unit": 4,
        "unitName": "Festivals & Celebrations",
        "week": 7,
        "date": "2026-08-18",
        "day": "Tue",
        "objective": "Explore two famous festivals of dance and drums.",
        "value": "Enthusiasm",
        "math": "Rhythm patterns & counting beats",
        "english": "Reading about festivals",
        "bible": "Miriam's song of celebration",
        "built": false
      },
      {
        "n": 21,
        "id": "a21",
        "title": "Panagbenga: The Flower Festival",
        "unit": 4,
        "unitName": "Festivals & Celebrations",
        "week": 7,
        "date": "2026-08-21",
        "day": "Fri",
        "objective": "Learn Baguio's flower festival and how flowers bloom.",
        "value": "Appreciation",
        "math": "Symmetry in flowers",
        "english": "Descriptive writing",
        "bible": "Consider the lilies — God's care",
        "built": false
      },
      {
        "n": 22,
        "id": "a22",
        "title": "Filipino Music & Instruments",
        "unit": 4,
        "unitName": "Festivals & Celebrations",
        "week": 8,
        "date": "2026-08-24",
        "day": "Mon",
        "objective": "Meet the kulintang, rondalla, and Filipino rhythm.",
        "value": "Creativity",
        "math": "Patterns & fractions in rhythm",
        "english": "Listening & new words",
        "bible": "The Psalms — songs of praise",
        "built": false
      },
      {
        "n": 23,
        "id": "a23",
        "title": "Make & Move: Festival Crafts & Dance",
        "unit": 4,
        "unitName": "Festivals & Celebrations",
        "week": 8,
        "date": "2026-08-25",
        "day": "Tue",
        "objective": "Make festival crafts and learn a simple dance.",
        "value": "Expression",
        "math": "Shapes & measuring (masks)",
        "english": "How-to instructions",
        "bible": "Using the talents God gave us",
        "built": false
      },
      {
        "n": 24,
        "id": "a24",
        "title": "Our Family Celebration Project",
        "unit": 4,
        "unitName": "Festivals & Celebrations",
        "week": 8,
        "date": "2026-08-28",
        "day": "Fri",
        "objective": "Plan and hold a small family celebration.",
        "value": "Togetherness",
        "math": "Planning a schedule (time)",
        "english": "Speaking & presenting",
        "bible": "Joyful gatherings together",
        "built": false
      }
    ]
  },
  {
    "n": 5,
    "name": "Land of Fire & Mountains",
    "adventures": [
      {
        "n": 25,
        "id": "a25",
        "title": "Fire Mountains: Volcanoes of the Philippines",
        "unit": 5,
        "unitName": "Land of Fire & Mountains",
        "week": 9,
        "date": "2026-08-31",
        "day": "Mon",
        "objective": "Explore volcanoes and the Ring of Fire.",
        "value": "Wonder",
        "math": "Rounding & big numbers (heights)",
        "english": "Vocabulary: erupt, magma, lava",
        "bible": "God speaks at Mt. Sinai",
        "built": true
      },
      {
        "n": 26,
        "id": "a26",
        "title": "Mayon, Taal & Pinatubo Up Close",
        "unit": 5,
        "unitName": "Land of Fire & Mountains",
        "week": 9,
        "date": "2026-09-01",
        "day": "Tue",
        "objective": "Compare three famous Philippine volcanoes.",
        "value": "Curiosity",
        "math": "Comparing numbers (>, <)",
        "english": "Compare & contrast writing",
        "bible": "God's power over creation",
        "built": false
      },
      {
        "n": 27,
        "id": "a27",
        "title": "The Ring of Fire & Our Earth",
        "unit": 5,
        "unitName": "Land of Fire & Mountains",
        "week": 9,
        "date": "2026-09-04",
        "day": "Fri",
        "objective": "Understand why our earth has volcanoes & quakes.",
        "value": "Awe",
        "math": "Simple maps & counting",
        "english": "Reading nonfiction",
        "bible": "The earth is the Lord's",
        "built": false
      },
      {
        "n": 28,
        "id": "a28",
        "title": "Mountains & Highlands",
        "unit": 5,
        "unitName": "Land of Fire & Mountains",
        "week": 10,
        "date": "2026-09-07",
        "day": "Mon",
        "objective": "Tour the tallest mountains and cool highlands.",
        "value": "Perseverance",
        "math": "Elevation & measurement",
        "english": "Descriptive writing",
        "bible": "Faith that moves mountains",
        "built": false
      },
      {
        "n": 29,
        "id": "a29",
        "title": "Tropical Weather: Wet & Dry Seasons",
        "unit": 5,
        "unitName": "Land of Fire & Mountains",
        "week": 10,
        "date": "2026-09-08",
        "day": "Tue",
        "objective": "Learn the two seasons and how weather works.",
        "value": "Preparedness",
        "math": "Reading a weather graph",
        "english": "Days & seasons vocabulary",
        "bible": "God gives the seasons (Noah)",
        "built": false
      },
      {
        "n": 30,
        "id": "a30",
        "title": "Science Project: Build a Volcano",
        "unit": 5,
        "unitName": "Land of Fire & Mountains",
        "week": 10,
        "date": "2026-09-11",
        "day": "Fri",
        "objective": "Build and safely 'erupt' a model volcano.",
        "value": "Discovery",
        "math": "Measuring ingredients",
        "english": "Recording observations",
        "bible": "God the Creator of all",
        "built": false
      }
    ]
  },
  {
    "n": 6,
    "name": "Amazing Filipino Wildlife",
    "adventures": [
      {
        "n": 31,
        "id": "a31",
        "title": "Amazing Animals of the Philippines",
        "unit": 6,
        "unitName": "Amazing Filipino Wildlife",
        "week": 11,
        "date": "2026-09-14",
        "day": "Mon",
        "objective": "Meet unique animals found only here.",
        "value": "Stewardship",
        "math": "Counting & graphing animals",
        "english": "Vocabulary: endemic, endangered",
        "bible": "God made every creature",
        "built": true
      },
      {
        "n": 32,
        "id": "a32",
        "title": "The Mighty Philippine Eagle",
        "unit": 6,
        "unitName": "Amazing Filipino Wildlife",
        "week": 11,
        "date": "2026-09-15",
        "day": "Tue",
        "objective": "Study the national bird and why it's endangered.",
        "value": "Protection",
        "math": "Wingspan measurement",
        "english": "Nonfiction reading",
        "bible": "Wings like eagles (Isaiah)",
        "built": false
      },
      {
        "n": 33,
        "id": "a33",
        "title": "The Tiny Tarsier",
        "unit": 6,
        "unitName": "Amazing Filipino Wildlife",
        "week": 11,
        "date": "2026-09-18",
        "day": "Fri",
        "objective": "Discover Bohol's big-eyed little primate.",
        "value": "Gentleness",
        "math": "Size comparison (small numbers)",
        "english": "Descriptive writing",
        "bible": "God cares for small creatures",
        "built": false
      },
      {
        "n": 34,
        "id": "a34",
        "title": "The Carabao: Farmer's Friend",
        "unit": 6,
        "unitName": "Amazing Filipino Wildlife",
        "week": 12,
        "date": "2026-09-21",
        "day": "Mon",
        "objective": "Learn about the hardworking national animal.",
        "value": "Diligence",
        "math": "Multiplication (work in the fields)",
        "english": "Reading comprehension",
        "bible": "Hard work is honored (Proverbs)",
        "built": false
      },
      {
        "n": 35,
        "id": "a35",
        "title": "Rainforest & Night Creatures",
        "unit": 6,
        "unitName": "Amazing Filipino Wildlife",
        "week": 12,
        "date": "2026-09-22",
        "day": "Tue",
        "objective": "Explore rainforest life and nocturnal animals.",
        "value": "Curiosity",
        "math": "Sorting habitats; counting",
        "english": "Creative writing: a night animal",
        "bible": "Day and night (Creation)",
        "built": false
      },
      {
        "n": 36,
        "id": "a36",
        "title": "Conservation Project: Protect Our Animals",
        "unit": 6,
        "unitName": "Amazing Filipino Wildlife",
        "week": 12,
        "date": "2026-09-25",
        "day": "Fri",
        "objective": "Create a project to help protect wildlife.",
        "value": "Responsibility",
        "math": "Data & tally (a survey)",
        "english": "Persuasive writing (a poster)",
        "bible": "Stewardship of creation",
        "built": false
      }
    ]
  },
  {
    "n": 7,
    "name": "Farms, Rice & the Land",
    "adventures": [
      {
        "n": 37,
        "id": "a37",
        "title": "The Rice Terraces: Stairways to the Sky",
        "unit": 7,
        "unitName": "Farms, Rice & the Land",
        "week": 13,
        "date": "2026-09-28",
        "day": "Mon",
        "objective": "Climb the ancient Banaue Rice Terraces.",
        "value": "Perseverance",
        "math": "Multiplication & patterns (rows)",
        "english": "Writing about hard work",
        "bible": "Ruth gleaning in the fields",
        "built": true
      },
      {
        "n": 38,
        "id": "a38",
        "title": "Life on a Filipino Farm",
        "unit": 7,
        "unitName": "Farms, Rice & the Land",
        "week": 13,
        "date": "2026-09-29",
        "day": "Tue",
        "objective": "Experience daily life and work on a farm.",
        "value": "Hard Work",
        "math": "Word problems (animals & crops)",
        "english": "Reading a day-in-the-life",
        "bible": "The parable of the sower",
        "built": false
      },
      {
        "n": 39,
        "id": "a39",
        "title": "From Seed to Harvest",
        "unit": 7,
        "unitName": "Farms, Rice & the Land",
        "week": 13,
        "date": "2026-10-02",
        "day": "Fri",
        "objective": "Follow a plant's life cycle from seed to harvest.",
        "value": "Patience",
        "math": "Time & sequencing (growth stages)",
        "english": "Sequence writing",
        "bible": "The seed grows (Mark 4)",
        "built": false
      },
      {
        "n": 40,
        "id": "a40",
        "title": "Coconuts: The Tree of Life",
        "unit": 7,
        "unitName": "Farms, Rice & the Land",
        "week": 14,
        "date": "2026-10-05",
        "day": "Mon",
        "objective": "Discover the many uses of the coconut tree.",
        "value": "Resourcefulness",
        "math": "Listing & counting uses",
        "english": "Nonfiction reading",
        "bible": "God's provision for us",
        "built": false
      },
      {
        "n": 41,
        "id": "a41",
        "title": "Garden Math: Fruits & Vegetables",
        "unit": 7,
        "unitName": "Farms, Rice & the Land",
        "week": 14,
        "date": "2026-10-06",
        "day": "Tue",
        "objective": "Practice measurement & multiplication in the garden.",
        "value": "Care",
        "math": "Measurement & multiplication",
        "english": "Labels & vocabulary",
        "bible": "Tending the garden (Eden)",
        "built": false
      },
      {
        "n": 42,
        "id": "a42",
        "title": "Grow Together: Plant a Seed Project",
        "unit": 7,
        "unitName": "Farms, Rice & the Land",
        "week": 14,
        "date": "2026-10-09",
        "day": "Fri",
        "objective": "Plant a real seed and start a family garden.",
        "value": "Nurturing",
        "math": "Measuring growth (cm) & charting",
        "english": "Observation journal",
        "bible": "Faith like a mustard seed",
        "built": false
      }
    ]
  },
  {
    "n": 8,
    "name": "Under the Sea",
    "adventures": [
      {
        "n": 43,
        "id": "a43",
        "title": "Under the Sea: Coral Reefs & Ocean Wonders",
        "unit": 8,
        "unitName": "Under the Sea",
        "week": 15,
        "date": "2026-10-12",
        "day": "Mon",
        "objective": "Dive into coral reefs and ocean life.",
        "value": "Courage",
        "math": "Multiplication (schools of fish)",
        "english": "Vocabulary: coral reef",
        "bible": "Jonah and the big fish",
        "built": true
      },
      {
        "n": 44,
        "id": "a44",
        "title": "The Coral Triangle & Tubbataha",
        "unit": 8,
        "unitName": "Under the Sea",
        "week": 15,
        "date": "2026-10-13",
        "day": "Tue",
        "objective": "Explore the center of ocean biodiversity.",
        "value": "Wonder",
        "math": "Big numbers & comparing",
        "english": "Nonfiction reading",
        "bible": "God made the seas",
        "built": false
      },
      {
        "n": 45,
        "id": "a45",
        "title": "Sea Turtles, Clownfish & Giant Clams",
        "unit": 8,
        "unitName": "Under the Sea",
        "week": 15,
        "date": "2026-10-16",
        "day": "Fri",
        "objective": "Meet amazing creatures of the Philippine seas.",
        "value": "Care",
        "math": "Counting & classifying",
        "english": "Descriptive writing",
        "bible": "God's care for every creature",
        "built": false
      },
      {
        "n": 46,
        "id": "a46",
        "title": "Keeping Our Oceans Clean",
        "unit": 8,
        "unitName": "Under the Sea",
        "week": 16,
        "date": "2026-10-19",
        "day": "Mon",
        "objective": "Learn how to protect the sea from pollution.",
        "value": "Stewardship",
        "math": "Data (litter tally & graph)",
        "english": "Persuasive writing",
        "bible": "Caring for the earth God gave",
        "built": false
      },
      {
        "n": 47,
        "id": "a47",
        "title": "Fishing Villages & the Sea's Gifts",
        "unit": 8,
        "unitName": "Under the Sea",
        "week": 16,
        "date": "2026-10-20",
        "day": "Tue",
        "objective": "Visit coastal life and the gifts of the sea.",
        "value": "Gratitude",
        "math": "Money & counting the catch",
        "english": "Reading about coastal life",
        "bible": "Jesus and the fishermen",
        "built": false
      },
      {
        "n": 48,
        "id": "a48",
        "title": "Ocean Art & Conservation Pledge",
        "unit": 8,
        "unitName": "Under the Sea",
        "week": 16,
        "date": "2026-10-23",
        "day": "Fri",
        "objective": "Make ocean art and a family conservation pledge.",
        "value": "Commitment",
        "math": "Symmetry & shapes",
        "english": "Writing a pledge",
        "bible": "Caring for God's world",
        "built": false
      }
    ]
  },
  {
    "n": 9,
    "name": "Heroes, History & Symbols",
    "adventures": [
      {
        "n": 49,
        "id": "a49",
        "title": "Filipino Heroes & Our Story",
        "unit": 9,
        "unitName": "Heroes, History & Symbols",
        "week": 17,
        "date": "2026-10-26",
        "day": "Mon",
        "objective": "Meet brave Filipino heroes and our country's story.",
        "value": "Leadership",
        "math": "Timeline & subtraction (years)",
        "english": "Public speaking: a hero I admire",
        "bible": "Brave Queen Esther",
        "built": true
      },
      {
        "n": 50,
        "id": "a50",
        "title": "Dr. José Rizal: The Hero Who Wrote",
        "unit": 9,
        "unitName": "Heroes, History & Symbols",
        "week": 17,
        "date": "2026-10-27",
        "day": "Tue",
        "objective": "Learn how Rizal used words to help his people.",
        "value": "Wisdom",
        "math": "Dates & timelines",
        "english": "Biography reading",
        "bible": "Solomon asks for wisdom",
        "built": false
      },
      {
        "n": 51,
        "id": "a51",
        "title": "Andrés Bonifacio & Everyday Heroes",
        "unit": 9,
        "unitName": "Heroes, History & Symbols",
        "week": 17,
        "date": "2026-10-30",
        "day": "Fri",
        "objective": "Honor a brave leader and everyday heroes.",
        "value": "Courage",
        "math": "Word problems",
        "english": "Opinion writing: what makes a hero",
        "bible": "David's courage",
        "built": false
      },
      {
        "n": 52,
        "id": "a52",
        "title": "Independence Day & Our Flag",
        "unit": 9,
        "unitName": "Heroes, History & Symbols",
        "week": 18,
        "date": "2026-11-02",
        "day": "Mon",
        "objective": "Celebrate freedom and the meaning of the flag.",
        "value": "Patriotism",
        "math": "Calendar & dates (June 12)",
        "english": "Reading comprehension",
        "bible": "Freedom (Moses leads the people)",
        "built": false
      },
      {
        "n": 53,
        "id": "a53",
        "title": "National Symbols: Sampaguita, Narra, Eagle",
        "unit": 9,
        "unitName": "Heroes, History & Symbols",
        "week": 18,
        "date": "2026-11-03",
        "day": "Tue",
        "objective": "Study the flower, tree, bird and more.",
        "value": "Pride",
        "math": "Sorting & matching",
        "english": "Vocabulary & labels",
        "bible": "God's good gifts to us",
        "built": false
      },
      {
        "n": 54,
        "id": "a54",
        "title": "Timeline Project: Our Country's Story",
        "unit": 9,
        "unitName": "Heroes, History & Symbols",
        "week": 18,
        "date": "2026-11-06",
        "day": "Fri",
        "objective": "Build a simple timeline of Philippine history.",
        "value": "Understanding",
        "math": "Ordering events on a number line",
        "english": "Summary writing",
        "bible": "Remembering God's works",
        "built": false
      }
    ]
  },
  {
    "n": 10,
    "name": "Regions Roadtrip",
    "adventures": [
      {
        "n": 55,
        "id": "a55",
        "title": "Manila: The Capital City",
        "unit": 10,
        "unitName": "Regions Roadtrip",
        "week": 19,
        "date": "2026-11-09",
        "day": "Mon",
        "objective": "Tour the busy, historic capital city.",
        "value": "Curiosity",
        "math": "City map: grids & coordinates",
        "english": "Nonfiction reading",
        "bible": "Cities in the Bible (intro)",
        "built": false
      },
      {
        "n": 56,
        "id": "a56",
        "title": "Cebu & the Heart of the Visayas",
        "unit": 10,
        "unitName": "Regions Roadtrip",
        "week": 19,
        "date": "2026-11-10",
        "day": "Tue",
        "objective": "Explore Cebu's history, beaches and food.",
        "value": "Adventure",
        "math": "Distance on a map",
        "english": "Travel writing",
        "bible": "Paul's journeys (intro)",
        "built": false
      },
      {
        "n": 57,
        "id": "a57",
        "title": "Bohol: Chocolate Hills & Tarsiers",
        "unit": 10,
        "unitName": "Regions Roadtrip",
        "week": 19,
        "date": "2026-11-13",
        "day": "Fri",
        "objective": "Visit the famous hills and tiny tarsiers.",
        "value": "Wonder",
        "math": "Estimating (1,200+ hills)",
        "english": "Descriptive writing",
        "bible": "God's amazing creation",
        "built": false
      },
      {
        "n": 58,
        "id": "a58",
        "title": "Palawan: The Last Frontier",
        "unit": 10,
        "unitName": "Regions Roadtrip",
        "week": 20,
        "date": "2026-11-16",
        "day": "Mon",
        "objective": "Discover Palawan's rivers, reefs and islands.",
        "value": "Appreciation",
        "math": "Measuring length (a river)",
        "english": "Nonfiction reading",
        "bible": "Rivers of living water",
        "built": false
      },
      {
        "n": 59,
        "id": "a59",
        "title": "Baguio: City of Pines",
        "unit": 10,
        "unitName": "Regions Roadtrip",
        "week": 20,
        "date": "2026-11-17",
        "day": "Tue",
        "objective": "Explore the cool mountain city and its flowers.",
        "value": "Freshness",
        "math": "Temperature & graphs",
        "english": "Compare-climates writing",
        "bible": "God's care in every season",
        "built": false
      },
      {
        "n": 60,
        "id": "a60",
        "title": "Vigan & the North: Old Streets & History",
        "unit": 10,
        "unitName": "Regions Roadtrip",
        "week": 20,
        "date": "2026-11-20",
        "day": "Fri",
        "objective": "Walk historic cobblestone streets up north.",
        "value": "Heritage",
        "math": "Time & history (old vs. new)",
        "english": "History reading",
        "bible": "Nehemiah rebuilds the walls",
        "built": false
      },
      {
        "n": 61,
        "id": "a61",
        "title": "Davao & Mindanao's Bounty",
        "unit": 10,
        "unitName": "Regions Roadtrip",
        "week": 21,
        "date": "2026-11-23",
        "day": "Mon",
        "objective": "Taste Davao's fruits and meet Mount Apo.",
        "value": "Gratitude",
        "math": "Multiplication (fruit harvest)",
        "english": "Descriptive writing",
        "bible": "Gratitude for God's provision",
        "built": false
      },
      {
        "n": 62,
        "id": "a62",
        "title": "Iloilo & Hiligaynon Country",
        "unit": 10,
        "unitName": "Regions Roadtrip",
        "week": 21,
        "date": "2026-11-24",
        "day": "Tue",
        "objective": "Visit the home of Hiligaynon and its heritage.",
        "value": "Belonging",
        "math": "Word problems",
        "english": "Hiligaynon reading & speaking",
        "bible": "Every language praises God",
        "built": false
      },
      {
        "n": 63,
        "id": "a63",
        "title": "Map Master Challenge: Tour the Philippines",
        "unit": 10,
        "unitName": "Regions Roadtrip",
        "week": 21,
        "date": "2026-11-27",
        "day": "Fri",
        "objective": "Take a grand map tour of everywhere we've been.",
        "value": "Mastery",
        "math": "Coordinates & distances (review)",
        "english": "Presentation skills",
        "bible": "Go to every place (Great Commission)",
        "built": false
      }
    ]
  },
  {
    "n": 11,
    "name": "Livelihood, Community & Getting Around",
    "adventures": [
      {
        "n": 64,
        "id": "a64",
        "title": "The Jeepney & Filipino Transportation",
        "unit": 11,
        "unitName": "Livelihood, Community & Getting Around",
        "week": 22,
        "date": "2026-11-30",
        "day": "Mon",
        "objective": "Ride the jeepney and learn how Filipinos travel.",
        "value": "Community",
        "math": "Fare & money math",
        "english": "Reading signs & vocabulary",
        "bible": "The journey of life",
        "built": false
      },
      {
        "n": 65,
        "id": "a65",
        "title": "Filipino Jobs & Livelihood",
        "unit": 11,
        "unitName": "Livelihood, Community & Getting Around",
        "week": 22,
        "date": "2026-12-01",
        "day": "Tue",
        "objective": "Explore jobs and practice money math.",
        "value": "Diligence",
        "math": "Money, wages & simple budgeting",
        "english": "Interviewing & speaking",
        "bible": "Working heartily (Colossians)",
        "built": false
      },
      {
        "n": 66,
        "id": "a66",
        "title": "Markets & Sari-Sari Stores",
        "unit": 11,
        "unitName": "Livelihood, Community & Getting Around",
        "week": 22,
        "date": "2026-12-04",
        "day": "Fri",
        "objective": "Learn trading, sari-sari stores, and change-making.",
        "value": "Enterprise",
        "math": "Money, change & simple profit",
        "english": "Persuasive / ad writing",
        "bible": "The parable of the talents",
        "built": false
      }
    ]
  },
  {
    "n": 12,
    "name": "Traditions & Family Celebrations  (fully configurable)",
    "adventures": [
      {
        "n": 67,
        "id": "a67",
        "title": "Filipino Family Traditions",
        "unit": 12,
        "unitName": "Traditions & Family Celebrations  (fully configurable)",
        "week": 23,
        "date": "2026-12-07",
        "day": "Mon",
        "objective": "Explore how Filipino families gather and celebrate — configurable to your family's own celebrations.",
        "value": "Hope",
        "math": "Counting down & calendars",
        "english": "Reading about traditions",
        "bible": "God's appointed Feasts — an overview (Leviticus 23)",
        "built": false
      },
      {
        "n": 68,
        "id": "a68",
        "title": "The Star Lantern: A Filipino Parol Craft",
        "unit": 12,
        "unitName": "Traditions & Family Celebrations  (fully configurable)",
        "week": 23,
        "date": "2026-12-08",
        "day": "Tue",
        "objective": "Craft a Filipino star lantern and learn the geometry of a star (a cultural craft, not tied to any holiday).",
        "value": "Creativity",
        "math": "Geometry: sides, angles, symmetry",
        "english": "How-to instructions",
        "bible": "God is our light",
        "built": false
      },
      {
        "n": 69,
        "id": "a69",
        "title": "Gathering & Gratitude",
        "unit": 12,
        "unitName": "Traditions & Family Celebrations  (fully configurable)",
        "week": 23,
        "date": "2026-12-11",
        "day": "Fri",
        "objective": "Discover the joy of gathering, hospitality and thankfulness — adaptable to your family's Feast Days.",
        "value": "Respect",
        "math": "Time & planning a gathering",
        "english": "Reading & discussion",
        "bible": "A thankful, gathered people",
        "built": false
      },
      {
        "n": 70,
        "id": "a70",
        "title": "A Family Feast Together",
        "unit": 12,
        "unitName": "Traditions & Family Celebrations  (fully configurable)",
        "week": 24,
        "date": "2026-12-14",
        "day": "Mon",
        "objective": "Plan a special family meal with recipe math and shared gratitude.",
        "value": "Generosity",
        "math": "Fractions & doubling recipes",
        "english": "Menu & recipe writing",
        "bible": "Sharing a feast (hospitality)",
        "built": false
      }
    ]
  },
  {
    "n": 13,
    "name": "Year-End Wonder Showcase",
    "adventures": [
      {
        "n": 71,
        "id": "a71",
        "title": "Our Journey Review: Passport & Map Recap",
        "unit": 13,
        "unitName": "Year-End Wonder Showcase",
        "week": 24,
        "date": "2026-12-15",
        "day": "Tue",
        "objective": "Review our passport, map and everything learned.",
        "value": "Reflection",
        "math": "Mixed review games",
        "english": "Summarizing our journey",
        "bible": "Giving thanks for the whole year",
        "built": false
      },
      {
        "n": 72,
        "id": "a72",
        "title": "Wonder Journey Showcase & Family Celebration",
        "unit": 13,
        "unitName": "Year-End Wonder Showcase",
        "week": 24,
        "date": "2026-12-18",
        "day": "Fri",
        "objective": "Celebrate the whole journey with a family showcase.",
        "value": "Celebration",
        "math": "Celebration data (badges & stamps)",
        "english": "Presentation & public speaking",
        "bible": "Go and share what you've learned",
        "built": false
      }
    ]
  }
]
};
if (typeof module !== "undefined") module.exports = { CURRICULUM_MAP };
